# Generated by Django 3.1.7 on 2021-02-20 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('report_name', models.CharField(max_length=200)),
                ('scan_date', models.DateField()),
                ('plugin_check_count', models.IntegerField(default=0)),
                ('severity_level_warning_count', models.IntegerField(default=0)),
                ('severity_level_minor_count', models.IntegerField(default=0)),
                ('severity_level_major_count', models.IntegerField(default=0)),
                ('severity_level_critical_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=2)),
                ('plugin_id', models.CharField(max_length=10)),
                ('plugin_name', models.CharField(max_length=200)),
                ('plugin_family', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('action', models.CharField(max_length=1000)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.report')),
            ],
        ),
    ]
