# Generated by Django 3.1.7 on 2021-02-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210220_1615'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemsfound',
            unique_together=set(),
        ),
    ]
